export const PropertiesActionTypes = {
    TOGGLE_PROPERTY_MODAL: 'TOGGLE_PROPERTY_MODAL',
    SET_CURRENT_PROPERTY: 'SET_CURRENT_PROPERTY',
    FILTER_PROPERTIES: 'FILTER_PROPERTIES'
};

export const PropertiesFiltersTypes = {
    PROPERTY_TYPE: 'PROPERTY_TYPE',
    BEDROOMS: 'BEDROOMS',
    BATHROOMS: 'BATHROOMS'
};

export const PropertiesTypes = {
    TERRACED: 'TERRACED',
    DETACHED: 'DETACHED',
    'SEMI_DETACHED': 'SEMI_DETACHED',
    APARTMENT: 'APARTMENT',
};
